### PR TITLE
SqlDelight Support

### PR DESCRIPTION
**Pull request by kageiit**
- Provides a generic framework to hook any third party gradle plugins that generate sources inside buck
- Add sqldelight support as an example

### CODE REVIEW

**Comment by kageiit** [comment]
build error seems unrelated. will fix it in a bit. but verified this works locally.

**Comment by kageiit** [comment]
This seems to run fine locally, but travis does not like multiple gradle processes invoked by buck.

@Piasy can you test this out on your machine?

**Comment by Piasy** [comment]
I've tested it yesterday, it works fine in my machine too.

**Comment by kageiit** [comment]
ok im trying some solutions from https://discuss.gradle.org/t/timeout-waiting-to-lock-artifact-cache/2545/14

**Comment by kageiit** [comment]
> ok im trying some solutions from https://discuss.gradle.org/t/timeout-waiting-to-lock-artifact-cache/2545/14

This did not work, so i put in a workaround to not have the buildSrc folder lying around when running inside buck (since it is not needed)

**Comment by Piasy** [comment]
Hope to see a release including this :)

**Comment by kageiit** [comment]
I am trying to get in espresso test support
plan to cut a release with that as well

**Comment by Piasy** [comment]
Great! I can wait for that 👍

**Pull request merged**
