### PR TITLE
fix local aar dependency resolve bug

### PR DESCRIPTION
**Pull request by Piasy**
when user have local aar dependency, there will be a NPE throw from dependency resolve:

```java
Caused by: java.lang.NullPointerException
	at org.apache.maven.artifact.versioning.ComparableVersion.parseVersion(ComparableVersion.java:357)
	at org.apache.maven.artifact.versioning.ComparableVersion.<init>(ComparableVersion.java:348)
	at org.apache.maven.artifact.versioning.DefaultArtifactVersion.parseVersion(DefaultArtifactVersion.java:112)
	at org.apache.maven.artifact.versioning.DefaultArtifactVersion.<init>(DefaultArtifactVersion.java:48)
	at com.github.okbuilds.core.dependency.ExternalDependency.<init>(ExternalDependency.groovy:13)
	at com.github.okbuilds.core.model.Scope$_extractConfigurations_closure2$_closure3.doCall(Scope.groovy:62)
	at com.github.okbuilds.core.model.Scope$_extractConfigurations_closure2.doCall(Scope.groovy:50)
	at com.github.okbuilds.core.model.Scope.extractConfigurations(Scope.groovy:46)
	at com.github.okbuilds.core.model.Scope.<init>(Scope.groovy:36)
	at com.github.okbuilds.core.model.AndroidTarget.getMain(AndroidTarget.groovy:55)
```

### CODE REVIEW

**Comment by kageiit** [comment]
I think it is better to just add a version to the local aar like `rxscreenshotdetector-1.0.0-release.aar`

**Comment by Piasy** [comment]
`rxscreenshotdetector-release.aar`, `rxscreenshotdetector-1.0.0-release.aar` and `rxscreenshotdetector-release-1.0.0.aar` will cause NPE.

**Comment by kageiit** [comment]
Looks good. Please rebase and merge once checks pass

**Comment by Piasy** [comment]
@kageiit ButterKnife support has NPE crash at app runtime, I'll merge this pr and cut a new release after travis pass. Could you please fix the crash later on master?

**Pull request merged**
