### PR TITLE
Install buck via gradle for travis

### PR DESCRIPTION
**Pull request by kageiit**

### CODE REVIEW

**Comment by Piasy** [comment]
in current directory, `buck@ -> ~/.gradle/caches/okbuilds/buck/bin/buck`, but in `~/.gradle/caches/okbuilds/buck`, it only contains a `.git` directory, nothing else, so travis can't find `buck` executable.

btw, could we ignore the `buck` link in pwd?

**Comment by kageiit** [comment]
- Simplified installation process
- Added waitFor to ensure git index does not get locked between git commands
- Make sure switching repositories and branches works

**Comment by Piasy** [comment]
Still fail.

btw, if we have run `buckInstall` task before, when I re-run it, would it rebuild buck binary?

**Comment by kageiit** [comment]
> btw, if we have run buckInstall task before, when I re-run it, would it rebuild buck binary?

yes it will. I deleted travis cache and rebuild it now to check one final time

**Comment by kageiit** [comment]
abandoning this. will open another

**Pull request closed without merging**
